### ISSUE TITLE
Configurable target property name

### ISSUE THREAD

**Issue by donpratt** [g3rv4/RandomForest#4]
Currently, this looks for a data field named "_target". Are you open to making this configurable?  I have a pmml file that a coworker created, but he used a more descriptive name for his output data field. I already made the change locally if you're open to a pull request (not that it's at all difficult).

**Comment by g3rv4** [comment]
sure! go for it! just keep the default to the current behavior ;)

**Comment by donpratt** [comment]
Thanks.  I just opened a pull request for this.  Pretty basic, but let me know if you have any questions or suggestions.

**Comment by g3rv4** [comment]
Merged! I’ll let you know once it’s on nuget

**Comment by donpratt** [comment]
Thanks.

**Comment by g3rv4** [comment]
Done! version 0.2.3 has been uploaded to nuget... it may take a couple hours for it to be indexed. Thanks a ton!
